"use client";
import {useEffect,useState} from "react"; import {supabase} from "../../lib/supabase";
const blank={name:"",category:"",price:"",old_price:"",image_url:"",redirect_url:"",description:"",badge:"",active:true};
export default function Admin(){const db=supabase(),[session,setSession]=useState(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[items,setItems]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[msg,setMsg]=useState("");
async function load(){let {data}=await db.from("products").select("*").order("created_at",{ascending:false});setItems(data||[])}
useEffect(()=>{db.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)load()});const {data:s}=db.auth.onAuthStateChange((_e,x)=>{setSession(x);if(x)load()});return()=>s.subscription.unsubscribe()},[]);
async function login(e){e.preventDefault();let {error}=await db.auth.signInWithPassword({email,password});setMsg(error?error.message:"Acesso autorizado")}
async function save(e){e.preventDefault();let p={...form,price:Number(form.price),old_price:form.old_price?Number(form.old_price):null};let r=editing?await db.from("products").update(p).eq("id",editing):await db.from("products").insert(p);if(r.error)return setMsg(r.error.message);setForm(blank);setEditing(null);setMsg("Produto salvo");load()}
async function del(id){if(confirm("Excluir produto?")){await db.from("products").delete().eq("id",id);load()}}
if(!session)return <main className="login"><form onSubmit={login}><a className="brand" href="/">VYRON<span>.</span></a><h1>Painel administrativo</h1><p>Entre com sua conta autorizada.</p><label>E-mail</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><label>Senha</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><button>Entrar</button><small>{msg}</small></form></main>;
return <main className="admin"><div className="adminTop"><div><a className="brand" href="/">VYRON<span>.</span></a><h1>Gerenciar produtos</h1></div><button onClick={()=>db.auth.signOut()}>Sair</button></div><div className="adminGrid"><form className="productForm" onSubmit={save}><h2>{editing?"Editar produto":"Novo produto"}</h2>{["name","category","price","old_price","image_url","redirect_url","badge"].map(k=><label key={k}>{({name:"Nome",category:"Categoria",price:"Preço",old_price:"Preço anterior",image_url:"URL da imagem",redirect_url:"Link de redirecionamento",badge:"Selo"}[k])}<input type={k==="redirect_url"?"url":k.includes("price")?"number":"text"} step=".01" value={form[k]||""} onChange={e=>setForm({...form,[k]:e.target.value})} required={k==="name"||k==="price"||k==="redirect_url"}/></label>)}<label>Descrição<textarea value={form.description||""} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Produto ativo</label><button>{editing?"Salvar alterações":"Publicar produto"}</button><small>{msg}</small></form><section className="manage"><h2>Catálogo ({items.length})</h2>{items.map(p=><div className="row" key={p.id}><img src={p.image_url||"https://placehold.co/100"}/><div><b>{p.name}</b><small>{p.category} · R$ {Number(p.price).toFixed(2)}</small></div><button onClick={()=>{setEditing(p.id);setForm({...blank,...p})}}>Editar</button><button className="danger" onClick={()=>del(p.id)}>Excluir</button></div>)}</section></div></main>}